# Version of the Render YAML schema
services:
  - type: web
    name: my-backend-service
    env: node  # or specify the environment type, such as 'python' or 'docker' if using Docker
    plan: free  # Use 'free' or any other plan name if you're on a paid plan
    buildCommand: "yarn install && yarn build"  # or npm commands like "npm install && npm run build"
    startCommand: "yarn start"  # command to start your server

    # Specify the directory if deploying a monorepo (where backend is in a subfolder)
    rootDir: ./easy-green-backend

    # Environment variables
    envVars:
      - key: DATABASE_URL
        value: "mysql://root:damilOlamide14$@localhost:3306/easy_green"


    # Health check path
    healthCheckPath: "/health"  # Render uses this to determine if your service is up

    # Auto deploy settings
    autoDeploy: true  # automatically deploy on git push

